version: '3.8'

services:
  db:
    image: postgres:15
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_PASSWORD: todolist@123
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfiles/Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: todolist@123
      DB_NAME: todolist
    depends_on:
      - db

volumes:
  postgres_data:
  frontend-build:
